apiVersion: v2
name: caderneta
description: Telegram bot for personal finance tracking
type: application
version: 0.4.1
appVersion: "0.4.1"
keywords:
  - telegram
  - bot
  - finance
home: https://github.com/RafaLG18/telegram-financas
sources:
  - https://github.com/RafaLG18/telegram-financas
maintainers:
  - name: RafaLG18
