"""schema inicial

Revision ID: f86e0739a29f
Revises: 
Create Date: 2026-08-18 23:03:29.578001
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f86e0739a29f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.CheckConstraint("tipo IN ('gasto','entrada','ambos')", name='ck_categoria_tipo'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('rascunho',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=10), nullable=True),
    sa.Column('valor_centavos', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('valor_centavos', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('conta_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('origem_update_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("tipo IN ('gasto','entrada')", name='ck_transacao_tipo'),
    sa.CheckConstraint('valor_centavos > 0', name='ck_transacao_valor_positivo'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origem_update_id')
    )
    with op.batch_alter_table('transacao', schema=None) as batch_op:
        batch_op.create_index('idx_transacao_data', ['data'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacao', schema=None) as batch_op:
        batch_op.drop_index('idx_transacao_data')

    op.drop_table('transacao')
    op.drop_table('rascunho')
    op.drop_table('categoria')
    # ### end Alembic commands ###
