{{- if not .Values.telegram.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-token" (include "caderneta.fullname" .) }}
  labels:
    {{- include "caderneta.labels" . | nindent 4 }}
type: Opaque
stringData:
  BOT_TOKEN: {{ .Values.telegram.botToken | quote }}
{{- end }}
